name: Sync default to main
on:
  push:
    branches:
      - 'default'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Sync default branch to main
        run: |
          git config user.name "Pantheon Automation"
          git config user.email "bot@getpantheon.com"
          git fetch --all
          git pull origin default
          git checkout main
          git merge --no-edit default
          git push origin main
